[[releases]]
version = "0.3.1"
date = "2026-02-07"
refs = ["WI-2026-02-07-001"]

[[releases]]
version = "0.3.0"
date = "2026-01-29"
refs = [
    "WI-2026-01-29-002",
    "WI-2026-01-29-003",
]

[[releases]]
version = "0.2.4"
date = "2026-01-29"
refs = ["WI-2026-01-29-001"]

[[releases]]
version = "0.2.3"
date = "2026-01-26"
refs = [
    "WI-2026-01-26-005",
    "WI-2026-01-26-006",
    "WI-2026-01-26-007",
    "WI-2026-01-26-008",
    "WI-2026-01-26-009",
    "WI-2026-01-26-010",
]

[[releases]]
version = "0.2.2"
date = "2026-01-26"
refs = [
    "WI-2026-01-26-001",
    "WI-2026-01-26-002",
    "WI-2026-01-26-003",
    "WI-2026-01-26-004",
]

[[releases]]
version = "0.2.1"
date = "2026-01-25"
refs = [
    "WI-2026-01-25-001",
    "WI-2026-01-25-002",
]

[[releases]]
version = "0.2.0"
date = "2026-01-19"
refs = [
    "WI-2026-01-18-003",
    "WI-2026-01-19-001",
    "WI-2026-01-19-002",
    "WI-2026-01-19-003",
    "WI-2026-01-19-004",
    "WI-2026-01-19-005",
    "WI-2026-01-19-006",
    "WI-2026-01-19-007",
    "WI-2026-01-19-008",
    "WI-2026-01-19-009",
    "WI-2026-01-19-010",
]

[[releases]]
version = "0.1.0"
date = "2026-01-18"
refs = [
    "WI-2026-01-17-001",
    "WI-2026-01-17-002",
    "WI-2026-01-17-003",
    "WI-2026-01-17-004",
    "WI-2026-01-17-005",
    "WI-2026-01-17-006",
    "WI-2026-01-17-007",
    "WI-2026-01-17-008",
    "WI-2026-01-17-009",
    "WI-2026-01-17-010",
    "WI-2026-01-17-011",
    "WI-2026-01-17-012",
    "WI-2026-01-17-013",
    "WI-2026-01-17-014",
    "WI-2026-01-17-015",
    "WI-2026-01-17-016",
    "WI-2026-01-17-017",
    "WI-2026-01-17-018",
    "WI-2026-01-17-019",
    "WI-2026-01-17-020",
    "WI-2026-01-17-021",
    "WI-2026-01-17-022",
    "WI-2026-01-17-023",
    "WI-2026-01-17-024",
    "WI-2026-01-17-025",
    "WI-2026-01-17-026",
    "WI-2026-01-17-027",
    "WI-2026-01-17-028",
    "WI-2026-01-17-029",
    "WI-2026-01-17-030",
    "WI-2026-01-18-001",
    "WI-2026-01-18-002",
]
