[phaseos]
schema = 1
id = "ADR-0001"
title = "Use TOML for ADRs and Work Items"
status = "proposed"
date = "2026-01-17"

[content]
context = """
Describe the context and problem statement.
What is the issue that we're seeing that is motivating this decision?"""
decision = """
Describe the decision that was made.
What is the change that we're proposing and/or doing?"""
consequences = """
Describe the resulting context after applying the decision.
What becomes easier or more difficult to do because of this change?"""
